# SPDX-FileCopyrightText: 2026 TerraLab <yvann.barbot@terra-lab.ai>
# SPDX-License-Identifier: GPL-2.0-or-later
"""QGIS Processing handlers: run/list/describe algorithms, plus the async task registry (QgsTask-backed) that run_processing(async=true)."""



from __future__ import annotations

from .layer_lookup import _find_layer  # noqa: F401 - importable here as before the split
from .processing_decisions import (  # noqa: F401 - moved here, re-exported for the callers of processing_tools
    _FIELD_EXISTS_RE,
    _LAYER_ERROR_RE,
    _NATIVE_TWIN,
    _NO_THREADING_FLAG,
    _PARAM_ERROR_RE,
    _SUBPROCESS_IMPORT_RE,
    _UNSAFE_PROCESSING_ALGORITHMS,
    _goes_to_task,
    _model_steps_may_leave,
    _processing_error,
    _threadable,
    _unsafe_processing_algorithm,
)
from .processing_destinations import (  # noqa: F401 - moved here, re-exported for the callers of processing_tools
    _FILE_EXTENSION_RE,
    _GPKG_TABLE_RE,
    _LAYER_INPUT_TYPES,
    _OGR_DBNAME_RE,
    _OPTIONAL_PROVIDERS,
    _destination_names,
    _ensure_proj_env,
    _fid_blocks_geopackage,
    _fid_safe_suffix,
    _gpkg_sink_uri,
    _gpkg_table_target,
    _has_proj_db,
    _input_file_paths,
    _inputs_as_layers,
    _is_optional,
    _missing_destinations,
    _missing_inputs,
    _names_a_kept_file,
    _output_names,
    _provider_hint,
    _reads_as_destination,
    _release_table_layers,
    _required_input_name,
)
from .processing_help import (  # noqa: F401 - moved here, re-exported for the callers of processing_tools
    _ALGORITHMS_CACHE,
    _ALGORITHMS_CACHE_COUNT,
    _get_algorithm_help,
    _list_algorithms,
    _parameter_help,
)
from .processing_run import (  # noqa: F401 - moved here, re-exported for the callers of processing_tools
    _ASYNC_FEATURES,
    _ASYNC_FILE_BYTES,
    _ASYNC_PIXELS,
    _FILE_EXTENSIONS,
    _LOG_LINE_CHARS,
    _LOG_LINES,
    _POLL_INTERVAL_S,
    _PROCESSING_TASKS,
    LEFTOVER_OUTPUTS,
    _cancel_task,
    _CapturingFeedback,
    _cleanup_canceled_destination,
    _declare_raster_crs,
    _drop_leftovers,
    _file_is_big,
    _get_task_status,
    _heavy_inputs,
    _inject_gdal_crs,
    _layer_summary,
    _list_tasks,
    _looks_like_file,
    _on_proc_done,
    _on_proc_progress,
    _on_proc_terminated,
    _plain_output,
    _process_outputs,
    _record_history,
    _report_empty_outputs,
    _report_log,
    _run_processing,
    _size_of,
    _start_async_processing,
    _sweep_consumed_tasks,
    _sync_with_qgis,
    canceled_output,
    raster_file_problem,
    register_task,
    shutdown,
)
